*Composed by Sirakorn Lamyai, Kasetsart University*

---

# Knowing NumPy

NumPy is a powerful mathematical library for Python. The main motivation behind NumPy is the need of a very powerful mathematical data structure with ease in mathematical-like operations

One of the examples I do really like is that given a vector $\vec{u}=2\hat{i}+3\hat{j}+4\hat{k}$ and $\vec{v}=3\hat{i}+4\hat{j}+5\hat{k}$, we can denote the two vectors in these two lists respectively:

In [1]:
vec_u_list = [2, 3, 4]
vec_v_list = [3, 4, 5]

Suppose we need to find the vector addition $\vec{u}+\vec{v}$, our first try is to plus the two lists directly (with the `+` operator)...

In [2]:
vec_u_list + vec_v_list

[2, 3, 4, 3, 4, 5]

It is noticed that this results into the concatenation of Python lists, an expected behaviour of lists.

Not a good try though, let's try it again with the `-` operator:

In [3]:
vec_u_list - vec_v_list

TypeError: unsupported operand type(s) for -: 'list' and 'list'

What happened?

__Thinking corner__: Why is this expected in Python? Why doesn't the standard is written is a fashion that the `+` and `-` operator will add and subtract the values respectively, index-wise?

# Importing NumPy

## Python imports

Many libraries aren't built-in directly into Python. Not only that such libraries should be installed manually, but also that they need to be imported prior to using them.

We could import the NumPy library as follows, straightforwardly:

In [4]:
import numpy

However, every time the elements from the NumPy library is used, we must explicitly refre that we're trying to use the function from the NumPy library, for example:

In [5]:
# Don't worry if you don't understand this!
_ = numpy.linspace(1, 10)

Typing `numpy` for several times is not fun. We could import NumPy with a shorthand `import ... as ...` syntax:

In [6]:
import numpy as np

And we could refer to NumPy as shortly as `np`!

In [7]:
# Totally equivalent to second above cell
_ = np.linspace(1, 10)

However, to cause less confusion, we're going to use the full `numpy` name, at least in this notebook.

## numpy.array

NumPy comes with a object type called __NumPy array__. We can simply convert any lists to NumPy array by calling `numpy.array()` around the value to be converted.

In [8]:
vec_u = numpy.array(vec_u_list)
vec_v = numpy.array(vec_v_list)

Let's check out on how the vector $\hat{u}$ is like

In [9]:
vec_u

array([2, 3, 4])

...also check its type

In [10]:
type(vec_u)

numpy.ndarray

## NumPy array's mathematical operation

By adding `vec_u` and `vec_v` together...

In [11]:
vec_u + vec_v

array([5, 7, 9])

... we found out that the result of $\vec{u}+\vec{v}$ is an element-wise addition as intended for vector addition. It could therefore be implied that `numpy.array` was designed for mathematical use as its very first purpose.

Not only that `numpy.array` has an element-wise addition, the other operators `-`, `*`, `/`, and `%` operated on `numpy.array` will result in the element-wise calculations!

In [12]:
vec_u

array([2, 3, 4])

In [13]:
vec_u + 2

array([4, 5, 6])

In [14]:
vec_u * 3

array([ 6,  9, 12])

__Example 1__: Find the calculation of the vector $2\hat{u}-v$

In [15]:
# Write a solution for example 1 here

## `numpy.arange()`

We can use a command `numpy.arange()` to create a range equivalent to Python's `range()` fuctions.

If you're not familiar with Python's `range()` function, its syntax is `range(start, exclusive stop, step)`

In [16]:
# Creates a range, starting from 5, stopping exclusively at 5,
# and increases with a step of 0.2
numpy.arange(1, 5, 0.2)

array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4,
       3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8])

## numpy.linspace()

`numpy.linspace(start, stop, n)` creates an array starting from `start`, stopping __inclusively__ at `stop`, with `n` amounts of data points in the array.

In [17]:
# Creates a range, starting from 0, stopping inclusively at 10,
# with 11 elements inside the list
numpy.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

__Example 2__: Create an array using `numpy.linspace` which is eqivalent to `numpy.arange(1, 5, 0.2)`

In [18]:
# Write a solution for example 2 here

__Example 3__: Create an array using `numpy.arange` which is eqivalent to `numpy.linspace(0, 10, 11)`

In [19]:
# Write a solution for example 3 here

## Multidimensional array

NumPy arrays don't limit up to only one dimension arrays. They can be used to create multidimensional arrays. This is an example for creating a 2D array, representing a matrix.

In [20]:
mat_a = numpy.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
mat_a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Array generators

We can create numpy arrays of zeros with `numpy.zeros()`...

In [21]:
# Creates array of zeros with [2, 3] as its size
numpy.zeros([2, 3])

array([[0., 0., 0.],
       [0., 0., 0.]])

...and create arrays of ones in the same manner with `numpy.ones()`

In [22]:
# Creates array of zeros with [4, 5] as its size
numpy.ones([4, 5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

`numpy.identity(n)` creates an identity matrix of $n \times n$

In [23]:
numpy.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Getting NumPy arrays' shapes

The shapes of NumPy arrays could be easily obtained with the `.shape` property

In [24]:
vec_u.shape

(3,)

In [25]:
mat_a.shape

(3, 3)

__Thinking corner__: What are the differences between Python's built-in lists and NumPy arrays that makes the `.shape` property built-in into NumPy, but not Python's lists?

## Slicing NumPy arrays

Let $B$ be the following matrix:

In [26]:
mat_b = numpy.array([
    [0.0, 0.1, 0.2, 0.3, 0.4],
    [1.0, 1.1, 1.2, 1.3, 1.4],
    [2.0, 2.1, 2.2, 2.3, 2.4],
    [3.0, 3.1, 3.2, 3.3, 3.4],
    [4.0, 4.1, 4.2, 4.3, 4.4]
])

We can slice the NumPy arrays as usual. The slicing below will select only a specific rows.

In [27]:
mat_b[0:2]

array([[0. , 0.1, 0.2, 0.3, 0.4],
       [1. , 1.1, 1.2, 1.3, 1.4]])

However, we can slice in the second dimension using the `,` dimension separator!

In [28]:
mat_b[0:2, 1:4]

array([[0.1, 0.2, 0.3],
       [1.1, 1.2, 1.3]])

We can also index the values multidimensionally!

In [29]:
mat_b[3, 4]

3.4

__Example 4__: Slice the matrix $B$ such that the output is equal to this matrix:

$$
\begin{bmatrix}
    2.2 & 2.3 & 2.4\\
    3.2 & 3.3 & 3.4
\end{bmatrix}
$$

In [30]:
# Write a solution for example 4 here

We can flatten the multidimensional array into a 1D array with the `ravel()` method:

In [31]:
mat_b.ravel()

array([0. , 0.1, 0.2, 0.3, 0.4, 1. , 1.1, 1.2, 1.3, 1.4, 2. , 2.1, 2.2,
       2.3, 2.4, 3. , 3.1, 3.2, 3.3, 3.4, 4. , 4.1, 4.2, 4.3, 4.4])

__Challenging question__: NumPy offers a `flat` attribute ([check out the docs](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.flat.html)). What are the differences between `flat` and `ravel()`?

# NumPy mathematical functions

NumPy comes with many mathematical functions, for example, given the matrix $M$ and $N$:

In [32]:
mat_m = numpy.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
# m = numpy.arange(9).reshape((3, 3))+1

mat_n = numpy.array([
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]
])
# n = numpy.arange(9, -1, -1).reshape((3, 3))

numpy.add(mat_m, mat_n)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [33]:
o = numpy.arange(0, 4.1, 0.2) * numpy.pi
# o = [0, 0.2*pi, 0.4*pi, ..., 2*pi]

sin_values = numpy.sin(o)
print(sin_values)

[ 0.00000000e+00  5.87785252e-01  9.51056516e-01  9.51056516e-01
  5.87785252e-01  1.22464680e-16 -5.87785252e-01 -9.51056516e-01
 -9.51056516e-01 -5.87785252e-01 -2.44929360e-16  5.87785252e-01
  9.51056516e-01  9.51056516e-01  5.87785252e-01  3.67394040e-16
 -5.87785252e-01 -9.51056516e-01 -9.51056516e-01 -5.87785252e-01
 -4.89858720e-16]


In [34]:
for sin_value in sin_values:
    print(" "*(int(sin_value*5)+5) + "*")
  
# This is some sin graph printing!

     *
       *
         *
         *
       *
     *
   *
 *
 *
   *
     *
       *
         *
         *
       *
     *
   *
 *
 *
   *
     *


We call those functions as __universal functions__. Some common universal functions are

* `add`
* `subtract`
* `multiply`
* `divide`
* `mod`
* `sqrt`
* `sin`
* `cos`
* `tan`
* `arcsin`
* `arccos`
* `arctan`

Check out the complete list of universal functions [here](https://docs.scipy.org/doc/numpy-1.13.0/reference/ufuncs.html#available-ufuncs).

## Matrix Functions

As we can represent matrices with NumPy arrays, let's use this time to demostrate the library's capabilities.

We generate some matrix representing some random numbers.

In [35]:
# สร้างเมทริกซ์เลขสุ่มของ [0, 1) ขนาด 4*4, คูณด้วย 10 แล้วแปลงเป็น int ทั้งหมด

mat_m = (numpy.random.rand(4,4)*10).astype(int)
mat_n = (numpy.random.rand(4,4)*10).astype(int)

In [36]:
mat_m

array([[5, 3, 0, 2],
       [1, 8, 4, 5],
       [5, 4, 5, 1],
       [3, 6, 7, 1]])

In [37]:
mat_n

array([[5, 9, 1, 0],
       [1, 6, 3, 9],
       [8, 8, 8, 4],
       [6, 4, 4, 6]])

We can reshape the matrix into the desired shape wth the `reshape()` method...

In [38]:
mat_m.reshape(8, 2)

array([[5, 3],
       [0, 2],
       [1, 8],
       [4, 5],
       [5, 4],
       [5, 1],
       [3, 6],
       [7, 1]])

and transpose the matrix with the `.T` property.

In [39]:
mat_m.T

array([[5, 1, 5, 3],
       [3, 8, 4, 6],
       [0, 4, 5, 7],
       [2, 5, 1, 1]])

## Matrix multiplication

The multiplication of `mat_m * mat_n` will yields the result of element-wise multiplication. ($(M*N)_{ij} = M_{ij} \times N_{ij}$)

In [40]:
mat_m * mat_n

array([[25, 27,  0,  0],
       [ 1, 48, 12, 45],
       [40, 32, 40,  4],
       [18, 24, 28,  6]])

NumPy offers a `numpy.dot()` function for matrix multiplication.

In [41]:
numpy.dot(mat_m, mat_n)

array([[ 40,  71,  22,  39],
       [ 75, 109,  77, 118],
       [ 75, 113,  61,  62],
       [ 83, 123,  81,  88]])

Also the exists `numpy.cross()` for __vector__ cross product.

In [42]:
numpy.cross(vec_u, vec_v)

array([-1,  2, -1])

### Determinants and Inverses

NumPy has a sub-library so called `numpy.linalg` for linear algebra tasks. For example, ones could calculate the determinant and the inverse of a matrix with `numpy.linalg.det()` and `numpy.linalg.inv()` respectively.

In [43]:
numpy.linalg.det(mat_m)

-180.0

In [44]:
numpy.linalg.inv(mat_m)

array([[ 0.1       , -0.05555556,  0.16111111, -0.08333333],
       [ 0.5       , -0.16666667, -0.91666667,  0.75      ],
       [-0.4       ,  0.11111111,  0.57777778, -0.33333333],
       [-0.5       ,  0.38888889,  0.97222222, -0.91666667]])

In [ ]:
numpy.dot(mat_m, numpy.linalg.inv(mat_m))
# Very nearby to an indentity matrix,
# values comes with a slight error due to how computers
# store decimal points.